import { CourseType } from "@/types/Course";


export const coursesData: CourseType[] = [
  {
    id: "0o02051402",
    title: "Tasty Metal Shirt",
    slug: "tasty-metal-shirt",
    category: "Men",
    thumbnail: "https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/7.webp",
    students: 0,
    price: "340.00",
    speaker: "Shipon Islam",
    date: "2025/09/26 at 8:00PM",
    status: "Draft",
  },
  {
    id: "0o17477864",
    title: "Modern Gloves",
    slug: "modern-gloves",
    category: "Women",
    thumbnail: "https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/3.webp",
    students: 0,
    price: "340.00",
    speaker: "Shipon Islam",
    date: "2025/09/26",
    status: "Publish",
  },
  {
    id: "0o02374305",
    title: "Rustic Steel Computer",
    slug: "rustic-steel-computer",
    category: "Couples",
    thumbnail: "https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/1.webp",
    students: 50,
    price: "948.00",
    speaker: "Shipon Islam",
    date: "2025/09/26",
    status: "Pending",
  },
  {
    id: "0o02602714",
    title: "Licensed Concrete Cheese",
    slug: "licensed-concrete-cheese",
    category: "Men",
    thumbnail: "https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/11.webp",
    students: 0,
    price: "853.00",
    speaker: "Apon Shekh",
    date: "2025/09/26",
    status: "Publish",
  },
  {
    id: "0o54011366",
    title: "Electronic Rubber Table",
    slug: "electronic-rubber-table",
    category: "Women",
    thumbnail: "https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/15.webp",
    students: 18,
    price: "881.00",
    speaker: "Alvi",
    date: "2025/09/26",
    status: "Draft",
  },
  {
    id: "0o24033230",
    title: "Gorgeous Bronze Gloves",
    slug: "gorgeous-bronze-gloves",
    category: "Couples",
    thumbnail: "https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/16.webp",
    students: 9,
    price: "124.00",
    speaker: "Apon Shekh",
    date: "2025/09/26",
    status: "Pending",
  },
  {
    id: "0o27342230",
    title: "Practical Steel Keyboard",
    slug: "practical-steel-keyboard",
    category: "Men",
    thumbnail: "https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/6.webp",
    students: 0,
    price: "890.00",
    speaker: "Apon Shekh",
    date: "2025/09/26",
    status: "Draft",
  },
  {
    id: "0o64235224",
    title: "Sleek Frozen Ball",
    slug: "sleek-frozen-ball",
    category: "Women",
    thumbnail: "https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/8.webp",
    students: 9,
    price: "980.00",
    speaker: "Alvi",
    date: "2025/09/26",
    status: "Publish",
  },
  {
    id: "0o63671734",
    title: "Ergonomic Frozen Pants",
    slug: "ergonomic-frozen-pants",
    category: "Couples",
    thumbnail: "https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/9.webp",
    students: 0,
    price: "289.00",
    speaker: "Apon Shekh",
    date: "2025/09/26",
    status: "Draft",
  },
  {
    id: "0o60206537",
    title: "Sleek Fresh Chair",
    slug: "sleek-fresh-chair",
    category: "Men",
    thumbnail: "https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/10.webp",
    students: 24,
    price: "587.00",
    speaker: "Shipon Islam",
    date: "2025/09/26",
    status: "Publish",
  },
  {
    id: "0o53505174",
    title: "Awesome Granite Chicken",
    slug: "awesome-granite-chicken",
    category: "Women",
    thumbnail: "https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/12.webp",
    students: 9,
    price: "581.00",
    speaker: "Apon Shekh",
    date: "2025/09/26",
    status: "Pending",
  },
  {
    id: "0o20360446",
    title: "Rustic Concrete Ball",
    slug: "rustic-concrete-ball",
    category: "Couples",
    thumbnail: "https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/4.webp",
    students: 18,
    price: "946.00",
    speaker: "Apon Shekh",
    date: "2025/09/26",
    status: "Publish",
  },
  {
    id: "0o05416424",
    title: "Electronic Concrete Computer",
    slug: "electronic-concrete-computer",
    category: "Men",
    thumbnail: "https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/13.webp",
    students: 24,
    price: "448.00",
    speaker: "Apon Shekh",
    date: "2025/09/26",
    status: "Draft",
  },
  {
    id: "0o52110435",
    title: "Small Wooden Pizza",
    slug: "small-wooden-pizza",
    category: "Women",
    thumbnail: "https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/14.webp",
    students: 0,
    price: "676.00",
    speaker: "Shipon Islam",
    date: "2025/09/26",
    status: "Publish",
  },
  {
    id: "0o40214300",
    title: "Tasty Bronze Salad",
    slug: "tasty-bronze-salad",
    category: "Couples",
    thumbnail: "https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/4.webp",
    students: 9,
    price: "524.00",
    speaker: "Shipon Islam",
    date: "2025/09/26",
    status: "Draft",
  },
  {
    id: "0o02061402",
    title: "Tasty Metal T-Shirt",
    slug: "tasty-metal-t-shirt",
    category: "Men",
    thumbnail: "https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/7.webp",
    students: 0,
    price: "400.00",
    speaker: "Alvi",
    date: "2025/09/26",
    status: "Pending",
  },
  {
    id: "0o17477064",
    title: "Modern Cotton Gloves",
    slug: "modern-cotton-gloves",
    category: "Women",
    thumbnail: "https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/3.webp",
    students: 0,
    price: "342.00",
    speaker: "Shipon Islam",
    date: "2025/09/26",
    status: "Publish",
  },
  {
    id: "0o02374335",
    title: "Steel Computer",
    slug: "steel-computer",
    category: "Couples",
    thumbnail: "https://isomorphic-furyroad.s3.amazonaws.com/public/products/modern/1.webp",
    students: 0,
    price: "948.00",
    speaker: "Alvi",
    date: "2025/09/26",
    status: "Draft",
  },
];
